# |------------------------------------------------------------------------
# |                           Файл конфигуарации
# |                           By DraimGooSe
# |
# |------------------------------------------------------------------------
config:
  refresh-gui: true
  refresh-delay: 20
  gui-blocks: true
  ingame-editor: true
  hotbar-items: true
  custom-commands: true
  auto-register-commands: false
  auto-update-gui: true # Авто-обнова гуишек
  server-ping-timeout: 10
  stop-sound: true
  disabled-world-message: true
  update-notifications: true
  gui-snooper: false
  format:
    tag: '&8(&cDMenu&8) &8> '
    perms: 'У вас нет прав.'
    reload: 'Перезагружено.'
    nomenu: 'Меню не найдено.'
    noitem: 'На панели нет кликабельного элемента.'
    notitem: 'Игрок не найден.'
    error: 'Найдена ошибка в конфигурации.'
    offline: 'Оффлайн'
    offlineHeadValue: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmU1Mjg2YzQ3MGY2NmZmYTFhMTgzMzFjYmZmYjlhM2MyYTQ0MjRhOGM3MjU5YzQ0MzZmZDJlMzU1ODJhNTIyIn19fQ=='
input:
  input-cancel: отмена
  input-cancelled: 'Отмененно!'
  input-message:
    - '%dm-tag%&aВвод команды для меню'
    - '&7Пропишите, &4%dm-args% &7чтобы отменить'
hexcodes:
  start_tag: '#'
  end_tag: ''
placeholders:
  primary:
    start: '%'
    end: '%'
  secondary:
    start: '{'
    end: '}'
updater:
  auto-update: true
  minor-updates-only: true
  update-checks: true
purchase:
  currency:
    success: '&7Успешно кулпено $%dm-args%'
    failure: '&7Недостаточно денег!'
  tokens:
    success: '&7Успешно куплено %dm-args% коинов.'
    failure: '&7Недостаточно жетонов!'
  item:
    success: '&7Успешно продано %dm-args%.'
    failure: '&7Нехватает предметов!'
  xp:
    success: '&7Успещно куплено за %dm-args% уровней опыта.'
    failure: '&7Нехватает опыта!'
